In [1]:
import numpy as np

In [6]:
x = np.random.rand(10, 2)

In [11]:
x

array([[0.61003054, 0.86497983],
       [0.78020553, 0.35495549],
       [0.67971385, 0.07485727],
       [0.97510183, 0.70198827],
       [0.620524  , 0.90327925],
       [0.57218587, 0.3322855 ],
       [0.45352073, 0.62896383],
       [0.47963475, 0.40403557],
       [0.04489054, 0.93856925],
       [0.51491236, 0.76699441]])

In [13]:
a=x[:,np.newaxis,:]

In [14]:
b=x[np.newaxis,:,:]

In [15]:
a,b

(array([[[0.61003054, 0.86497983]],
 
        [[0.78020553, 0.35495549]],
 
        [[0.67971385, 0.07485727]],
 
        [[0.97510183, 0.70198827]],
 
        [[0.620524  , 0.90327925]],
 
        [[0.57218587, 0.3322855 ]],
 
        [[0.45352073, 0.62896383]],
 
        [[0.47963475, 0.40403557]],
 
        [[0.04489054, 0.93856925]],
 
        [[0.51491236, 0.76699441]]]), array([[[0.61003054, 0.86497983],
         [0.78020553, 0.35495549],
         [0.67971385, 0.07485727],
         [0.97510183, 0.70198827],
         [0.620524  , 0.90327925],
         [0.57218587, 0.3322855 ],
         [0.45352073, 0.62896383],
         [0.47963475, 0.40403557],
         [0.04489054, 0.93856925],
         [0.51491236, 0.76699441]]]))

In [17]:
c=(a-b)**2

In [19]:
rsum=np.sum(c,axis=2)

In [21]:
rsum.shape

(10, 10)

In [22]:
rsum.diagonal()

array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0.])

In [23]:
rsum.argsort(axis=1)

array([[0, 4, 9, 6, 3, 7, 5, 1, 8, 2],
       [1, 5, 2, 7, 3, 6, 9, 0, 4, 8],
       [2, 5, 1, 7, 6, 3, 9, 0, 4, 8],
       [3, 1, 0, 4, 9, 6, 5, 7, 2, 8],
       [4, 0, 9, 6, 3, 7, 1, 5, 8, 2],
       [5, 7, 1, 2, 6, 9, 0, 3, 4, 8],
       [6, 9, 7, 0, 5, 4, 1, 8, 3, 2],
       [7, 5, 6, 1, 9, 2, 0, 4, 3, 8],
       [8, 9, 6, 0, 4, 7, 5, 1, 3, 2],
       [9, 0, 6, 4, 7, 5, 3, 1, 8, 2]], dtype=int64)