In [1]:
import torch
x=torch.randn(64,100)
y=torch.randn(64,10)

model=torch.nn.Sequential(
    torch.nn.Linear(100,50),
    torch.nn.ReLU(),
    torch.nn.Linear(50,10)
)

loss_fn=torch.nn.MSELoss(reduction='sum')

for t in range(500):
    y_pred=model(x)
    loss=loss_fn(y_pred,y)
    print(t,loss.item())
    model.zero_grad()
    loss.backward()
    with torch.no_grad():
        for param in model.parameters():
            param-=0.0001*param.grad

0 674.1134643554688
1 665.6615600585938
2 657.6637573242188
3 650.0797729492188
4 642.86962890625
5 635.9899291992188
6 629.4172973632812
7 623.1334838867188
8 617.103271484375
9 611.27587890625
10 605.653076171875
11 600.205810546875
12 594.915283203125
13 589.7871704101562
14 584.7852172851562
15 579.9200439453125
16 575.1939086914062
17 570.5671997070312
18 566.0303344726562
19 561.587646484375
20 557.2323608398438
21 552.9734497070312
22 548.7857666015625
23 544.6495361328125
24 540.5848999023438
25 536.5700073242188
26 532.61328125
27 528.7123413085938
28 524.8547973632812
29 521.0354614257812
30 517.2484741210938
31 513.5204467773438
32 509.82427978515625
33 506.1824645996094
34 502.5693664550781
35 498.99078369140625
36 495.4279479980469
37 491.8879089355469
38 488.35186767578125
39 484.8333435058594
40 481.317138671875
41 477.84063720703125
42 474.37005615234375
43 470.9267883300781
44 467.50506591796875
45 464.11138916015625
46 460.7236633300781
47 457.34332275390625
48 453.97

383 20.084632873535156
384 19.914104461669922
385 19.745765686035156
386 19.577571868896484
387 19.411457061767578
388 19.248394012451172
389 19.086496353149414
390 18.92344093322754
391 18.765090942382812
392 18.604509353637695
393 18.448556900024414
394 18.2928409576416
395 18.138429641723633
396 17.985414505004883
397 17.837417602539062
398 17.684566497802734
399 17.53610610961914
400 17.388641357421875
401 17.24411964416504
402 17.09996795654297
403 16.955766677856445
404 16.812213897705078
405 16.672380447387695
406 16.533466339111328
407 16.395322799682617
408 16.258811950683594
409 16.122272491455078
410 15.987340927124023
411 15.854748725891113
412 15.722746849060059
413 15.591004371643066
414 15.459754943847656
415 15.330740928649902
416 15.202913284301758
417 15.075082778930664
418 14.948529243469238
419 14.82399845123291
420 14.700911521911621
421 14.579046249389648
422 14.456690788269043
423 14.335888862609863
424 14.217477798461914
425 14.100513458251953
426 13.98384475708

In [2]:
import torch
x=torch.randn(64,100)
y=torch.randn(64,10)

model=torch.nn.Sequential(
    torch.nn.Linear(100,50),
    torch.nn.ReLU(),
    torch.nn.Linear(50,10)
)

loss_fn=torch.nn.MSELoss(reduction='sum')

optimizer = torch.optim.Adam(model.parameters(), lr=0.0001)
for t in range(500):
    y_pred=model(x)
    loss=loss_fn(y_pred,y)
    print(t,loss.item())
    model.zero_grad()
    loss.backward()
    optimizer.step()

0 648.94580078125
1 647.3570556640625
2 645.77587890625
3 644.2031860351562
4 642.6412353515625
5 641.0855102539062
6 639.53857421875
7 638.000244140625
8 636.476806640625
9 634.9613647460938
10 633.4539794921875
11 631.9539794921875
12 630.4618530273438
13 628.9756469726562
14 627.4943237304688
15 626.0198364257812
16 624.5514526367188
17 623.0932006835938
18 621.6432495117188
19 620.202392578125
20 618.7684326171875
21 617.3438110351562
22 615.9295043945312
23 614.5213623046875
24 613.1220092773438
25 611.7271728515625
26 610.3379516601562
27 608.9593505859375
28 607.5855712890625
29 606.2162475585938
30 604.8525390625
31 603.4935913085938
32 602.1407470703125
33 600.7991943359375
34 599.46484375
35 598.1345825195312
36 596.8121337890625
37 595.4935302734375
38 594.1799926757812
39 592.8711547851562
40 591.5685424804688
41 590.2733154296875
42 588.9823608398438
43 587.6967163085938
44 586.41748046875
45 585.1450805664062
46 583.876953125
47 582.6119995117188
48 581.3519897460938
49 5

400 261.0727844238281
401 260.306640625
402 259.5433349609375
403 258.7823181152344
404 258.0213928222656
405 257.26104736328125
406 256.5045471191406
407 255.7478485107422
408 254.99273681640625
409 254.23934936523438
410 253.48638916015625
411 252.736328125
412 251.98751831054688
413 251.23834228515625
414 250.48944091796875
415 249.74411010742188
416 249.00050354003906
417 248.2585906982422
418 247.5157012939453
419 246.7751007080078
420 246.0375213623047
421 245.29931640625
422 244.5618438720703
423 243.8263397216797
424 243.09219360351562
425 242.36007690429688
426 241.63116455078125
427 240.90272521972656
428 240.17410278320312
429 239.44932556152344
430 238.7253875732422
431 238.00318908691406
432 237.280517578125
433 236.55789184570312
434 235.84010314941406
435 235.1219024658203
436 234.40255737304688
437 233.68572998046875
438 232.96971130371094
439 232.2559814453125
440 231.54330444335938
441 230.83164978027344
442 230.12071228027344
443 229.41012573242188
444 228.7024993896

In [8]:
# -*- coding: utf-8 -*-
import random
import torch


class DynamicNet(torch.nn.Module):
    def __init__(self, D_in, H, D_out):
        """
        In the constructor we construct three nn.Linear instances that we will use
        in the forward pass.
        """
        super(DynamicNet, self).__init__()
        self.input_linear = torch.nn.Linear(D_in, H)
        self.middle_linear = torch.nn.Linear(H, H)
        self.output_linear = torch.nn.Linear(H, D_out)

    def forward(self, x):
        """
        For the forward pass of the model, we randomly choose either 0, 1, 2, or 3
        and reuse the middle_linear Module that many times to compute hidden layer
        representations.

        Since each forward pass builds a dynamic computation graph, we can use normal
        Python control-flow operators like loops or conditional statements when
        defining the forward pass of the model.

        Here we also see that it is perfectly safe to reuse the same Module many
        times when defining a computational graph. This is a big improvement from Lua
        Torch, where each Module could be used only once.
        """
        h_relu = self.input_linear(x).clamp(min=0)
        for _ in range(3):
            h_relu = self.middle_linear(h_relu).clamp(min=0)
        y_pred = self.output_linear(h_relu)
        return y_pred


# N is batch size; D_in is input dimension;
# H is hidden dimension; D_out is output dimension.
N, D_in, H, D_out = 1, 1, 1, 1

# Create random Tensors to hold inputs and outputs
x = torch.randn(N, D_in)
y = torch.randn(N, D_out)

# Construct our model by instantiating the class defined above
model = DynamicNet(D_in, H, D_out)

# Construct our loss function and an Optimizer. Training this strange model with
# vanilla stochastic gradient descent is tough, so we use momentum
criterion = torch.nn.MSELoss(reduction='sum')
optimizer = torch.optim.SGD(model.parameters(), lr=1e-4, momentum=0.9)
for t in range(500):
    # Forward pass: Compute predicted y by passing x to the model
    y_pred = model(x)
    
    
    # Compute and print loss
    loss = criterion(y_pred, y)
    print(t, loss.item())

    # Zero gradients, perform a backward pass, and update the weights.
    optimizer.zero_grad()
    loss.backward()
    optimizer.step()
    


0 4.624853610992432
1 4.6200056076049805
2 4.610803127288818
3 4.597698211669922
4 4.581104755401611
5 4.561398983001709
6 4.5389227867126465
7 4.5139875411987305
8 4.486876487731934
9 4.45784330368042
10 4.427120208740234
11 4.3949151039123535
12 4.3614182472229
13 4.326796531677246
14 4.291203498840332
15 4.254775524139404
16 4.217637538909912
17 4.179897785186768
18 4.14165735244751
19 4.103001117706299
20 4.064010143280029
21 4.024753570556641
22 3.985295534133911
23 3.9456899166107178
24 3.905987024307251
25 3.8662307262420654
26 3.826458692550659
27 3.7867062091827393
28 3.7470030784606934
29 3.7073755264282227
30 3.667847156524658
31 3.6284379959106445
32 3.5891659259796143
33 3.550046443939209
34 3.511092185974121
35 3.472315549850464
36 3.433725357055664
37 3.3953306674957275
38 3.3571383953094482
39 3.3191542625427246
40 3.2813830375671387
41 3.2438290119171143
42 3.2064952850341797
43 3.169384241104126
44 3.132497787475586
45 3.095837354660034
46 3.059404134750366
47 3.02319

428 5.554353776915377e-08
429 5.200560337925708e-08
430 4.868924463607982e-08
431 4.558388866371388e-08
432 4.2630063035176136e-08
433 3.987032926033862e-08
434 3.734102449470811e-08
435 3.4850074825953925e-08
436 3.261710901369952e-08
437 3.062473297177348e-08
438 2.8614422831196862e-08
439 2.6789294338414038e-08
440 2.506203600205481e-08
441 2.3501854684582213e-08
442 2.1991809262544848e-08
443 2.063451631784119e-08
444 1.928732729084004e-08
445 1.8017601632891456e-08
446 1.68839164871315e-08
447 1.578706587679335e-08
448 1.4813977600169892e-08
449 1.384377412705362e-08
450 1.2933526249980787e-08
451 1.2132886695326306e-08
452 1.1307065506116487e-08
453 1.0583804055386281e-08
454 9.908163178806717e-09
455 9.25480492242059e-09
456 8.69027871885919e-09
457 8.186603395188286e-09
458 7.614517016918398e-09
459 7.1435266590924584e-09
460 6.66808830374066e-09
461 6.227821813808987e-09
462 5.820766091346741e-09
463 5.445045303531515e-09
464 5.115907697472721e-09
465 4.764061145579035e-09
466

In [18]:
for param in model.parameters():
        print (param)
print(model)

Parameter containing:
tensor([[-0.4730]], requires_grad=True)
Parameter containing:
tensor([-0.7115], requires_grad=True)
Parameter containing:
tensor([[0.5373]], requires_grad=True)
Parameter containing:
tensor([0.7504], requires_grad=True)
Parameter containing:
tensor([[-1.2146]], requires_grad=True)
Parameter containing:
tensor([0.0576], requires_grad=True)
DynamicNet(
  (input_linear): Linear(in_features=1, out_features=1, bias=True)
  (middle_linear): Linear(in_features=1, out_features=1, bias=True)
  (output_linear): Linear(in_features=1, out_features=1, bias=True)
)


In [17]:
import numpy as np
x =torch.tensor([[5.0]])
model(x)

tensor([[-1.6068]], grad_fn=<AddmmBackward>)

In [5]:
# -*- coding: utf-8 -*-
"""
Created on Thu Jul  5 14:22:03 2018

@author: guokai_liu
"""

import torch
from torchvision import models
from torchsummary import summary

device = torch.device('cuda' if torch.cuda.is_available() else 'cpu')
vgg = models.vgg16().to(device)

summary(vgg, (3, 224, 224))

----------------------------------------------------------------
        Layer (type)               Output Shape         Param #
            Conv2d-1         [-1, 64, 224, 224]           1,792
              ReLU-2         [-1, 64, 224, 224]               0
            Conv2d-3         [-1, 64, 224, 224]          36,928
              ReLU-4         [-1, 64, 224, 224]               0
         MaxPool2d-5         [-1, 64, 112, 112]               0
            Conv2d-6        [-1, 128, 112, 112]          73,856
              ReLU-7        [-1, 128, 112, 112]               0
            Conv2d-8        [-1, 128, 112, 112]         147,584
              ReLU-9        [-1, 128, 112, 112]               0
        MaxPool2d-10          [-1, 128, 56, 56]               0
           Conv2d-11          [-1, 256, 56, 56]         295,168
             ReLU-12          [-1, 256, 56, 56]               0
           Conv2d-13          [-1, 256, 56, 56]         590,080
             ReLU-14          [-1, 256,